/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke651.wlt.server;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class ServerTest {
    @Test void serverHasAGreeting() {
        Server classUnderTest = new Server();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
