/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke651.wlt.server;

public class Server {
    public static void main(String[] args) {
        try {
            System.out.println("Game Start!");
            GameController gameController = new GameController();
            gameController.startGame();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Some error happens! Please restart the game!");
        }

        System.out.println("Game over!");
    }
}
