/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke651.wlt.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientTest {
    @Test void clientHasAGreeting() {
        Client classUnderTest = new Client();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
