/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke651.wlt.client;

public class Client {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Client().getGreeting());
    }
}
