/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke651.wlt.client;

public class Client {
    public static void main(String[] args) {
        try {
            ClientController clientController = new ClientController();
            clientController.startGame();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Some error happens! Please restart the game!");
        }
    }
}
